sonar.projectKey=litethinking-backend
sonar.projectName=LiteThinking Backend
sonar.projectVersion=1.0
sonar.organization=lucho118

# Directorio raíz del proyecto
sonar.sources=.
sonar.python.version=3.12

# Excluir directorios innecesarios
sonar.exclusions=**/.venv/**,**/migrations/**,**/__pycache__/**,**/tests/**,**/node_modules/**,.git/**,**/*.egg-info/**

# Directorios a analizar específicamente
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=apps,config,domain,manage.py

# Tests
sonar.tests=apps/*/tests
sonar.python.xunit.reportPath=test-results.xml
