# Generated by Django 4.2.30 on 2026-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueAuditoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Índice')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('entidad', models.CharField(max_length=50, verbose_name='Entidad')),
                ('entidad_id', models.CharField(db_index=True, max_length=50, verbose_name='ID entidad')),
                ('accion', models.CharField(max_length=10, verbose_name='Acción')),
                ('datos', models.JSONField(verbose_name='Datos')),
                ('hash_anterior', models.CharField(max_length=64, verbose_name='Hash anterior')),
                ('hash_actual', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash actual')),
            ],
            options={
                'verbose_name': 'Bloque de auditoría',
                'verbose_name_plural': 'Bloques de auditoría',
                'db_table': 'auditoria_cadena',
                'ordering': ['indice'],
            },
        ),
    ]
