# Generated by Django 4.2.30 on 2026-07-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(max_length=3, verbose_name='Moneda origen')),
                ('moneda_destino', models.CharField(max_length=3, verbose_name='Moneda destino')),
                ('tasa', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Tasa')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'db_table': 'tasas_cambio',
                'unique_together': {('moneda_origen', 'moneda_destino')},
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('caracteristicas', models.TextField(blank=True, verbose_name='Características')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio base')),
                ('moneda_base', models.CharField(default='COP', max_length=3, verbose_name='Moneda base')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresas.empresamodel', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
    ]
