# Generated by Django 4.2.30 on 2026-07-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_add_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProductoModel',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código de producto')),
                ('total_consultas', models.PositiveIntegerField(default=0, verbose_name='Total de consultas')),
            ],
            options={
                'verbose_name': 'Consulta de producto',
                'verbose_name_plural': 'Consultas de productos',
                'db_table': 'consultas_productos',
            },
        ),
    ]
